# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6af98063494a41a6dc1e113c75f88110016525fdcc112098232439bcb4376ff87f4afe3e19f6d9e2a29efb1b03d8563c0397146c145b8f922c5ee46e5a0bcee8

test:
  secret_key_base: e239704b3b3a038b83cec6e37f0b13f14119290b119a40814eea9ebaef9a48e7c8c14e39cbeecd0f9177b3b3211c1c8e078acf94fd4ded581376799bbe6c17a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
